language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
deploy:
  provider: cargo
  token:
    secure: G/y6eHKjKtPMmNkFoRa6+ujL4PRuTZxaL0j53CIg4PxdNPxJl0TRQgnKzspkXSoIN3UCZ1teOuyBUUIRDeOV4Ug9R1547gDLsyc8bbrXRy8CVs0qza3AOduct6KrHUxfIxUkHgQFqY8Xm9YU7XZsFTZmr755geMZs7b8YS8NO/tjD+vWTPaqqvXwH2O6iGT3VEdm4vr0MKQnuFvY83UIuclZTYWJ/JG8NGT8xZqqTdctlA8qAJhyZ9+C4ni69P7tErJAAYTyidCo++cng9Pkovg1qmvKE8m8GPvcXpXuCdEJbVlNu92LQq2cr2X8WnbbMwJg4VZEmyfiA/2KXsZ9iHwPu/WpQEmkCMiRIGujDZiEhRiX+3kMdpPe/WZqI/K/CGsAlWKX/SpSHC1mp2s3ziQPnRk7DlGs0Xo3ALyYUMa9Obn+oODEWmJltkxi7G7CrX6f155FVUup1VqA4rBJq6JQICiQTEHCaewYSVvFsWSXDJTkJKt+e+fgnVs6Ql5A79EUlx8FDalRe/rtPfCv1EQgLiLOeDUDizEL1eRJWrdhYKFA1kQgFdQeRkpfHqwkdJAI4zyZ5pZ6iYCxEBtqajiygAJEOptw7h6ugjQ+Ybzu/DFVmlR8kOMFiuv0uAWfQr2N14+HJmW/8B2HXLkjLWeuXkDcxfbRMsKuyO/93Ec=
  on:
    branch: master
    tags: true
    rust: stable
