language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly

deploy:
- provider: script
  script: scripts/deploy.sh
  on:
    branch: master
    tags: true
    rust: stable
