language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
deploy:
  provider: cargo
  token:
    secure: LJ/7rfdyUnk/vqUIje/tkoIdrrxTG2lgiftEIAEi4juJRF914a/k0Ef3A0HYgrLU4/u+QpWLB2ieFPksggkikPQwXnoGE9ggq14UqxNeKpTZ19Col5F8v9y7CPnrUCtvIZ1RFEQg0M3O+w2Wz12N2dFu4CF8MuQ6/sGLtoXNIyztbgp2mvCmi2dZOIGxCOqwm57sImUfX1KwumFCmaTYzRc2nbtPjHDBWpt1sAubVPN+OZUYrhW4s+dMzmz1gtkoIMs8IJBQETDstVdkl5cCyCgixUCp7Dqv7aH81XCdqfS+mhCtjoLJaf4doccpOZz/W3ubi5xrf8OD3xuV7pwVfUiMQMYWjM+nf/6HTaYwKy2GH1chYED6LLmv42n6sf+OPmbxre7OXUtz9jm85g1sMCCNvNMMXXUm1ShAAFnkclEvR08F9sKiBrqr7Ky4IB6Bu8l5iNV4ACocS/dRJBfhyd8b+UIEhZ3eOKvCF9+9vfpAuUV+Tn3W1Y1ghS18NI756qvpJR5RoWP3ZpnNvU3ZWaQULcrLymci8LbejdLocUrPrwUTLAgmUcvHgnr493IuB7fulaKIaoVLv6nlFykHRj/qZkQZiMMcvvTqOL/1vygRK3e6I8EPe4PXcdm7IGPHgZV0v57QJlv55BEZuAbyG3v/hfnN8gYqSHUGqDV7CUI=
  on:
    branch: master
    tags: true
    rust: stable
