language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
deploy:
  provider: cargo
  token:
    secure: IA2tySyioXWWvLpVqFV5aoBcpz4RqliqpFqPYvJmNNA5TW1ZW9ujVNepqYqwsZwNw0T7HVXO1Nk39t171FsvVhESzoXx89yuUGTBhllq8wo6VbY7EGdkSdI0rGecQ82bPSn6H/cRuKOElWaZt3AYve+5yMGo5kJU4Dd/OBjgCM4qSgvdu8bYLZHBWXO6iiUc/s7C0B44RjkJYRp9bd5V040rC0MaQ2XPv+GXJalmlZ4+ozklci8T+y3gjl/v0i2PIdrHMkqC0V2otC9eKIEofZfUAaV9hyJD6p87M7WeuJpLA9M1cAkS4bF78U4K0dRvYTWx3vd8FLiQ8e1wD6BvH/5dEfcg4kbtNaJSDQHnnwnFKZMh30jSgot1uuSoI294Lsfh2TlXa1B4/frM7Wir+Z7LJqbLQAQ1nXhXXgILvcDLp1hJywsNMYrYL2Vijr3yh0UXsGC1SlFYP1emBeJU26V6Ka1W4Lh2Da09ab/5Fryv6CDkw+X5C7vFUoYYP5rjMy3EBulpiIjzr6+qr23weXyvOeUFapZ7O6fcJx9iVdIJYejl2cxFNta0plNEBoEEQZG9QwNPbzK6mhPAbu+neDj6MUAGhdlKWkaDSyz5WV+mo8GnUVALnQlFfCLJZSRoYCIiqebiLrgC3FQoNgrBF0kQUAcvXY8en8cOcSqV8EM=
  on:
    branch: master
    tags: true
    rust: stable
