language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
deploy:
  provider: cargo
  token:
    secure: z1qM5IB3FfHFpCjM+ArhCJKBTDAzhPsvjZphnsbOrnSY0HmMfX+OaWMn9neXzJ+HuezmhsfXu8K8ax7mo+Pyaf4wYDIeM964BMiBJpQVveJFg5kZ0QEW++sY/IYHlAepvElVCEkDBP25X1iVg/9S6TkMolHzKm0St58KcEON4vSnb+SRnCwpIQcGeUBhIFAvcNvCmLjvuJ+gH389901JD5SsVwvU56c3fFfTJ5M4HcTVcTn+EGRYWby5UhI+zOTU05W4WkwDRbqo9VDgNKBlQ5jZq/tY26CT3KeS3YjpW+JUZI3hwMI8zZLNUDGSTzR0NrkzoRlGCErIjFfoL7Goh7EoAm03L2LFMJhkwP6ZQQa+UGR+PqwVuP8gs7ouafR6bAM+Uzk9aCvuW+fhIp9uvGiCRqvyux4eDnSsRiPPqWMCMhMBAmomJ6arK24NbvUGih3DFNIa+L7n8pqrJhjKDnLK7V1Vk6503+ZBD2v3Do2yQh8V2cmKdLUkiBmTXRMkvigw3P8npdAqFKzxGpWCExRHeaBYqBpo+ZhemJbIcQq6py8VgN1Rsyc+ohVJXaCTglsaqj+QjS0fKemd9CGuScbosWfQklOY4qe3vVEJB701JDJd1IV5UnjQPX3veQEwPlckr1hiOAznuPaolqI9ETowOokc8muSAvb7RhlWlfU=
  on:
    branch: master
    tags: true
    rust: stable
